build:
    image: rzarouali/alpine-serverspec

publish:
  docker:
    username: $$DOCKER_USERNAME 
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ocm-cabot
    tag: $${BRANCH/master/latest}
    file: Dockerfile
    insecure: true
    when:
      repo: ocm-cabot
      branch: [develop, master]
#    when:
#      branch: master
    #environment:
    # - DOCKER_LAUNCH_DEBUG=true

plugin:
  name: Docker
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: plugins/drone-docker
  labels:
    - docker
    - image
    - container

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/a6d76ff8fbc9d3d7d7e8


plugin:
  name: Gitter
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: plugins/drone-gitter
  labels:
    - notify
    - gitter
    - container
